// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfAldMo7Xl0_cmZi6ejblILg8MtY8hdw8',
    appId: '1:147576229933:web:61ab2f2ce0babc1909e8a4',
    messagingSenderId: '147576229933',
    projectId: 'fir-41e12',
    authDomain: 'fir-41e12.firebaseapp.com',
    storageBucket: 'fir-41e12.appspot.com',
    measurementId: 'G-BQ5QB9FX7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3F6ITmlj88zUzZzYA2l9OEZ8ghP9Dkks',
    appId: '1:147576229933:android:b06cc98519f5305309e8a4',
    messagingSenderId: '147576229933',
    projectId: 'fir-41e12',
    storageBucket: 'fir-41e12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxz7ZysYrC1D1a52PUb45FB3c-ojCXDTU',
    appId: '1:147576229933:ios:41f5a1242a194be109e8a4',
    messagingSenderId: '147576229933',
    projectId: 'fir-41e12',
    storageBucket: 'fir-41e12.appspot.com',
    iosClientId: '147576229933-qglssan4b8tej9les2jfr8k0st319427.apps.googleusercontent.com',
    iosBundleId: 'com.example.dash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxz7ZysYrC1D1a52PUb45FB3c-ojCXDTU',
    appId: '1:147576229933:ios:65ada70d95776fd109e8a4',
    messagingSenderId: '147576229933',
    projectId: 'fir-41e12',
    storageBucket: 'fir-41e12.appspot.com',
    iosClientId: '147576229933-ngkllm2tsfhbh4hqj47j4edbdfusn4qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.dash.RunnerTests',
  );
}
