// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA-AKFY67ZXAzR7kiIKK-UZJcIkR6-f0c',
    appId: '1:205809805471:web:47d5fee13f86cfacfa1aaa',
    messagingSenderId: '205809805471',
    projectId: 'dashchat2',
    authDomain: 'dashchat2.firebaseapp.com',
    storageBucket: 'dashchat2.appspot.com',
    measurementId: 'G-21YNPY9EDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3N-wHjnNnR3N1Bc07zDB2QSwfa38f7Rg',
    appId: '1:205809805471:android:64bee73f7d781cb2fa1aaa',
    messagingSenderId: '205809805471',
    projectId: 'dashchat2',
    storageBucket: 'dashchat2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa-ypwICV1ZJp3RCiN5kP3Q-HxCN8QpX0',
    appId: '1:205809805471:ios:448471d89f050780fa1aaa',
    messagingSenderId: '205809805471',
    projectId: 'dashchat2',
    storageBucket: 'dashchat2.appspot.com',
    iosClientId: '205809805471-15r7tig4npp0nfvmmgqnti0tg6tqpmlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.dash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa-ypwICV1ZJp3RCiN5kP3Q-HxCN8QpX0',
    appId: '1:205809805471:ios:16028dde9bd3492cfa1aaa',
    messagingSenderId: '205809805471',
    projectId: 'dashchat2',
    storageBucket: 'dashchat2.appspot.com',
    iosClientId: '205809805471-5v6hamvlln4g1empu907c5n2t42qd6nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.dash.RunnerTests',
  );
}
